# -*- coding: utf-8 -*-
"""tsid4_doc_v3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SGi-vL_liIQ6Fu1q2aBL8ra1ChwCjzRr
"""

from google.cloud import storage
from google.oauth2 import service_account

# from google.colab import auth
# auth.authenticate_user()
import subprocess
import os
import sys
project_id = os.getenv("project_id")  # 替換為您的 Google Cloud 專案 ID
command = f"gcloud config set project {project_id}"
try:
    # 运行命令
    subprocess.run(command, shell=True, check=True)
    print(f"Successfully set project to {project_id}")
    # print(sys.argv)
except subprocess.CalledProcessError as e:
    print(f"Error setting project: {e}")


# 全域服務帳戶密鑰文件路徑和 storage_client
credentials = service_account.Credentials.from_service_account_file('tsid4-411810-c5a23a3561b4.json')
storage_client = storage.Client(credentials=credentials)

"""Blob 版本取得"""

"""上傳檔案到Googld Cloud Storage 並獲取檔案資訊(包含版本資訊)"""

import requests

def download_file(url):
    """从指定的 URL 下载文件，返回响应对象"""
    response = requests.get(url)
    response.raise_for_status()  # 确保请求成功
    return response

def upload_blob_from_url(bucket_name, destination_blob_name, url):
    """從 URL 下載文件並上傳到 Google Cloud Storage"""
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)

    response = download_file(url)

    # 上传文件内容
    blob.upload_from_string(response.content)

    print(f"文件從 {url} 下載並上傳到 {destination_blob_name}.")

if __name__ == "__main__":
    # 假设你在调用时传递了参数，第一个参数是文件的 URL，第二个参数是目标 blob 名称
    file_url = sys.argv[1]
    destination_blob_name = sys.argv[2]
    # 假设你的 Google Cloud Storage bucket 名称是 'tsid4-bucket'
    bucket_name = 'tsid4-bucket'

    upload_blob_from_url(bucket_name, destination_blob_name, file_url)

    print("上傳成功!")

"""下載檔案"""
